replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.9.0-debian-12-r1
  pullPolicy: IfNotPresent

auth:
  clientProtocol: plaintext # Disable SASL/SSL for client communication
  interBrokerProtocol: plaintext # Disable SASL/SSL for inter-broker communication
  sasl:
    enabled: false # Disable SASL
    jaas:
      enabled: false # Disable JAAS
  tls:
    enabled: false # Disable TLS encryption

allowPlaintextListener: true # Enable PLAINTEXT listener explicitly

listeners:
  plaintext:
    port: 9092 # PLAINTEXT listener port

zookeeper:
  enabled: true
  auth:
    enabled: false # Disable Zookeeper authentication

## Persistence configuration
persistence:
  enabled: true
  size: 8Gi # Adjust size as needed