controller:
  replicaCount: 1 # Enable KRaft controllers for metadata management

kafka:
  replicaCount: 3 # Number of Kafka brokers

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.9.0-debian-12-r1
  pullPolicy: IfNotPresent

# Disable SASL and TLS authentication
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
    jaas:
      enabled: false
  tls:
    enabled: false

allowPlaintextListener: true # Explicitly allow PLAINTEXT listener

# Listeners configuration (multiple listeners)
listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT
    sslClientAuth: ""  # No SSL/TLS client authentication

  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT
    sslClientAuth: ""  # No SSL/TLS client authentication

  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT
    sslClientAuth: ""  # No SSL/TLS client authentication

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""  # No SSL/TLS client authentication

# Zookeeper configuration (disable authentication)
zookeeper:
  enabled: true
  auth:
    enabled: false  # Disable Zookeeper authentication

# External access
externalAccess:
  enabled: false  # Disable external access by default

# Persistence settings
persistence:
  enabled: true
  size: 8Gi