apiVersion: v1
kind: Service
metadata:
  name: java-auth-service
  namespace: default  # Change this if your pod is in a different namespace
spec:
  selector:
    name: java-auth-pod  # This should match the pod's labels
  ports:
    - protocol: TCP
      port: 8082         # Port on which the service is exposed
      targetPort: 8082   # Port on which the pod is listening