logging.level:
  org.springframework.jdbc.core: debug
  org.springframework.kafka: debug
  org.apache.kafka: debug

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresql-dev:5432/tvksp_prac8
    username: app
    password: root
  liquibase:
    change-log: classpath:db/changelog/java-producer-liquibase-master.xml

spring.kafka:
  admin.auto-create: true
  bootstrap-servers: my-kafka:9092