logging.level:
  org.springframework.jdbc.core: debug
  org.springframework.kafka: debug
  org.apache.kafka: debug

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresql-dev:5432/tvksp_prac8
    username: app
    password: root
  liquibase:
    change-log: classpath:db/changelog/java-producer-liquibase-master.xml

spring.kafka:
  admin.auto-create: true
  bootstrap-servers: my-kafka:9092
#  properties:
#    sasl:
#      mechanism: SCRAM-SHA-256
#      security.protocol: SASL_PLAINTEXT
#      jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="scCEiQsotr";'
  producer:
    key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value-serializer: "org.apache.kafka.common.serialization.StringSerializer"

# Password can be taken from: kubectl get secret my-kafka-user-passwords --namespace default -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1